/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.jsx',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'monastic-saffron': '#FF9933',
                'academic-maroon': '#800000',
                'parchment-bg': '#F9F7F2',
                'on-primary-fixed': '#2e1500',
                'secondary-container': '#fe624e',
                'on-tertiary-fixed-variant': '#5f4115',
                'surface-container': '#ededf3',
                'on-primary-fixed-variant': '#6d3a00',
                'secondary-fixed-dim': '#ffb4a8',
                'on-surface': '#1a1c20',
                'background': '#f9f9fe',
                'surface-dim': '#d9dadf',
                'surface-container-low': '#f3f3f9',
                'on-error-container': '#93000a',
                'secondary-fixed': '#ffdad4',
                'on-surface-variant': '#554336',
                'on-tertiary': '#ffffff',
                'on-background': '#1a1c20',
                'surface-container-lowest': '#ffffff',
                'surface': '#f9f9fe',
                'text-muted': '#5C5E62',
                'inverse-primary': '#ffb77a',
                'on-primary-container': '#693800',
                'surface-container-high': '#e8e8ed',
                'primary-container': '#ff9933',
                'text-primary': '#212327',
                'on-tertiary-fixed': '#2a1800',
                'on-error': '#ffffff',
                'surface-tint': '#8f4e00',
                'on-tertiary-container': '#5c3e13',
                'tertiary': '#7a582b',
                'on-secondary': '#ffffff',
                'on-secondary-container': '#650000',
                'on-secondary-fixed': '#410000',
                'primary-fixed': '#ffdcc2',
                'on-primary': '#ffffff',
                'tertiary-fixed': '#ffddb6',
                'tertiary-fixed-dim': '#ecbf88',
                'surface-variant': '#e2e2e7',
                'surface-bright': '#f9f9fe',
                'outline-variant': '#dbc2b0',
                'primary': '#8f4e00',
                'error': '#ba1a1a',
                'outline': '#887364',
                'tertiary-container': '#d5aa75',
                'inverse-surface': '#2e3035',
                'error-container': '#ffdad6',
                'secondary': '#b22b1d',
                'on-secondary-fixed-variant': '#8f0f07',
                'primary-fixed-dim': '#ffb77a',
                'surface-container-highest': '#e2e2e7',
                'inverse-on-surface': '#f0f0f6',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                'stack-sm': '8px',
                'margin-mobile': '16px',
                'stack-md': '16px',
                'section-gap': '80px',
                'container-max': '1200px',
                'gutter': '24px',
                'stack-lg': '32px',
            },
            fontFamily: {
                'google-sans': ['Google Sans', 'Inter', 'Noto Sans Lao', 'sans-serif'],
                'body-lg': ['Google Sans', 'Inter', 'Noto Serif Lao', 'sans-serif'],
                'headline-lg': ['Libre Caslon Text', 'Noto Serif Lao', 'serif'],
                'headline-display': ['Libre Caslon Text', 'Noto Serif Lao', 'serif'],
                'body-md': ['Google Sans', 'Inter', 'Noto Serif Lao', 'sans-serif'],
                'headline-lg-mobile': ['Libre Caslon Text', 'Noto Serif Lao', 'serif'],
                'label-caps': ['Work Sans', 'Noto Sans Lao', 'sans-serif'],
            },
        },
    },
    plugins: [],
};
